Repository bomctl/bomctl, pull requests merged in 2024-09, with the labels that each got.

#152 chore: enable protogetter and varnamelen linters
  .golangci.yml
  cmd/export.go
  cmd/list.go
  internal/pkg/client/git/client_test.go
  internal/pkg/client/git/push.go
  internal/pkg/client/git/push_test.go
  internal/pkg/client/oci/fetch.go
  internal/pkg/db/db_test.go
  internal/pkg/export/export.go
  internal/pkg/fetch/fetch.go
  internal/pkg/merge/merge.go
  internal/pkg/merge/merge_test.go
  internal/pkg/merge/merger.go
  internal/pkg/push/push.go
Labels: enhancement

#157 fix: license headers incorrectly interpreted as package documentation
  .github/scripts/check-go-headers.sh
  .github/workflows/golangci-lint.yml
  .taskfiles/lint.yml
  .vscode/header.code-snippets
  Makefile
  cmd/export.go
  cmd/fetch.go
  cmd/import.go
  cmd/list.go
  cmd/merge.go
  cmd/options.go
  cmd/push.go
  cmd/root.go
  cmd/version.go
  internal/pkg/client/client.go
  internal/pkg/client/git/client.go
  internal/pkg/client/git/client_test.go
  internal/pkg/client/git/fetch.go
  internal/pkg/client/git/internal_test.go
  internal/pkg/client/git/push.go
  internal/pkg/client/git/push_test.go
  internal/pkg/client/http/client.go
  internal/pkg/client/http/fetch.go
  internal/pkg/client/http/fetch_test.go
  internal/pkg/client/http/push.go
  internal/pkg/client/oci/client.go
  internal/pkg/client/oci/fetch.go
  internal/pkg/client/oci/fetch_test.go
  internal/pkg/client/oci/push.go
  internal/pkg/db/db.go
  internal/pkg/db/db_test.go
  internal/pkg/export/export.go
  internal/pkg/fetch/fetch.go
  internal/pkg/import/import.go
  internal/pkg/logger/logger.go
  internal/pkg/merge/merge.go
  internal/pkg/merge/merge_test.go
  internal/pkg/merge/merger.go
  internal/pkg/merge/merger_test.go
  internal/pkg/options/options.go
  internal/pkg/push/push.go
  internal/pkg/url/auth.go
  internal/pkg/url/url.go
  main.go
Labels: bug, documentation

#153 feat: document annotations for source data, hash, format, and URL
  .vscode/settings.json
  cmd/fetch.go
  cmd/root.go
  go.mod
  go.sum
  internal/pkg/client/git/client_test.go
  internal/pkg/client/git/push_test.go
  internal/pkg/db/db.go
  internal/pkg/db/db_test.go
  internal/pkg/fetch/fetch.go
  internal/pkg/import/import.go
  internal/pkg/merge/merge.go
  internal/pkg/merge/merge_test.go
  internal/pkg/push/push.go
  internal/pkg/url/url.go
Labels: enhancement

#163 refactor: add sliceutils helper package for dev convenience
  internal/pkg/sliceutils/sliceutils.go
  internal/pkg/sliceutils/sliceutils_test.go
Labels: enhancement

#155 refactor: stage all externally referenced SBOMs before push
  .golangci.yml
  go.mod
  internal/pkg/client/client.go
  internal/pkg/client/git/client.go
  internal/pkg/client/git/client_test.go
  internal/pkg/client/git/fetch.go
  internal/pkg/client/git/internal_test.go
  internal/pkg/client/git/push.go
  internal/pkg/client/git/push_test.go
  internal/pkg/client/http/client_test.go
  internal/pkg/client/http/push.go
  internal/pkg/client/oci/client_test.go
  internal/pkg/client/oci/push.go
  internal/pkg/db/db.go
  internal/pkg/fetch/fetch.go
  internal/pkg/import/import.go
  internal/pkg/push/push.go
Labels: enhancement

#165 fix: Print DocID for list cmd. Dynamic id/alias column width
  .github/workflows/golangci-lint.yml
  README.md
  cmd/list.go
  go.mod
  internal/pkg/outpututils/table.go
Labels: bug, enhancement

#175 ci: skip title check for dependabot PRs
  .github/workflows/commitlint.yml
Labels: bug
