Repository bomctl/bomctl, pull requests merged in 2024-06, with the labels that each got.

#73 refactor: update to use Protobom Ent backend
  README.md
  cmd/root.go
  go.mod
  go.sum
  internal/pkg/db/db.go
  internal/pkg/db/db_test.go
  internal/pkg/fetch/fetch.go
  internal/pkg/fetch/git/git.go
  internal/pkg/fetch/http/http.go
  internal/pkg/fetch/oci/oci.go
  internal/pkg/utils/utils.go
Labels: enhancement

#74 ci: add go test workflow
  .github/workflows/go-test.yml
  .gitignore
  Makefile
  internal/pkg/fetch/git/git.go
  internal/pkg/fetch/git/git_test.go
  internal/pkg/fetch/http/http.go
  internal/pkg/fetch/http/http_test.go
  internal/pkg/fetch/oci/oci_test.go
Labels: enhancement

#78 chore(docs): Update Steps to Contribute
  CONTRIBUTING.md
Labels: documentation

#82 feat: list command
  cmd/fetch.go
  cmd/list.go
  cmd/root.go
  go.mod
  go.sum
  internal/pkg/db/db.go
  internal/pkg/fetch/fetch.go
  internal/pkg/fetch/http/http.go
  internal/pkg/url/url.go
Labels: enhancement

#86 fix: update to protobom/storage@v0.1.3
  .github/workflows/golangci-lint.yml
  .golangci.yml
  .goreleaser.yml
  go.mod
  go.sum
Labels: bug

#87 chore: adding make install target
  .editorconfig
  .vscode/settings.json
  Makefile
Labels: enhancement
